### ISSUE TITLE
독일어에서 두 단어 합성어의 발음에 대한 처리 문제

### ISSUE THREAD

**Issue by karipe** [sublee/hangulize#14]
외래어 표기법의 독일어 표기 세칙을 보면 영어의 표기 세칙을 준용한다고 되어있고, 영어의 표기 세칙에는 다음과 같은 내용이 있습니다.
- 따로 설 수 있는 말의 합성으로 이루어진 복합어는 그것을 구성하고 있는 말이 단독으로 쓰일 때의 표기대로 적는다.

따라서, Mondlicht 같은 경우 Mond와 licht로 나눠도 각각 다 말이 되기 때문에 몬들리히트가 아니라 몬트리히트라 쓰는 것이 맞고, 현재 Hangulize에는 이런 부분에 대한 고려가 되어있지 않은 것으로 보입니다.

**Comment by sublee** [comment]
https://github.com/hangulize/hangulize/issues/3 에서 이어서 추적하겠습니다.
