### ISSUE TITLE
독일어 nk 표기

### ISSUE THREAD

**Issue by anemochore** [sublee/hangulize#20]
어쩌면 #14 와 같은 문제일 수도 있습니다.
Steinkirch 같은 인명을 질의하면 '슈타잉키르히'라고 나옵니다.
근데 외래어표기 용례를 보면 다음과 같이 kirche를 한 단어로 보는 듯합니다.

- Gelsenkirchen 겔젠키르헨
- Hallenkirche 할렌키르헤
- Garmisch-Partenkirchen 가르미슈파르텐키르헨

따라서 Steinkirch 역시 '슈타인키르히'로 표기하는 게 옳을 듯한데, 이를 구현하기는 어려울까요?
기존 용례가 있을 경우 합성어로 처리하는 규칙 같은 게 있다면 가능할 것도 같아 건의를 드려봅니다.

**Comment by sublee** [comment]
@iceager 님 확인해주실 수 있나요?

**Comment by sublee** [comment]
https://github.com/hangulize/hangulize/issues/3 에서 이어서 추적하겠습니다.
