### ISSUE TITLE
러시아 원어(Tchaikovsky)의 미변환 오류

### ISSUE THREAD

**Issue by Maybee1004** [sublee/hangulize#8]
원어 : Tchaikovsky
언어 : 러시아어
예상되는 한글 표기 : 차이콥스키
잘못된 변환 결과 : tchaikovsky
오류 내용 : 러시아어에서 'Tchaikovsky'를 입력하면 '차이콥스키'라는 한글 표기로 변환되어야 하는데 
한글 표기 대신에 원어가 그대로 표시됨.

**Comment by sublee** [comment]
이 논의는 예전에 한글라이즈 메일링 그룹에서 더 진행되었었습니다. 당시 @iceager 님의 답변을 첨부합니다:

> 러시아어의 로마자 표기는 중국어의 한어병음처럼 널리 쓰이는 방식이 없습니다. 말씀드린 것처럼 언어마다 표기 방식이 다를 뿐만이 아니라 각 언어에서 쓰는 표기 방식도 체계적이지 않습니다. 러시아어의 ч는 영어에서 보통 ch로 쓰지만 Чайковский의 ч는 특이하게 tch로 옮겨 Tchaikovsky라고 씁니다. 같은 한국어 이름도 사람마다 로마자 표기를 다르게 하는 것처럼 같은 러시아어 이름도 Andrey와 Andrei, Andrej, Nadia와 Nadya, Nadja 등으로 여러 표기를 쓸 수 있습니다. 거기다 옛 소련 여권에서 쓰던 로마자 표기는 프랑스어식을 기준으로 했기 때문에 널리 알려진 로마자 표기가 꼭 영어식이라고 단정할 수도 없습니다(전 테니스 선수 '쿠르니코바'는 프랑스어식 로마자 표기인 Kournikova로 널리 알려져 있습니다). 그러니 로마자 표기에서 원 키릴 문자 표기를 복원하는 것도 간단한 문제가 아닙니다.
