### ISSUE TITLE
변환 결과 평가 시스템

### ISSUE THREAD

**Issue by sublee** [sublee/hangulize#9]
@Maybee1004 님의 의견:

> 아래와 같은 형식으로 개별 변환결과에 대해 의견을 표명하여 공개하면 신뢰성 또는 오류에 대한 정보를 제공할 수 있을 것이
> 라고 생각합니다.
> 
> [찬성] - [반대] - [중립]
> 의견의 내용 :

변환 결과에 대한 +/- 버튼을 사이트에 비치하고 - 선택 시 다른 표기법을 제시할 수 있도록 합니다. 중립과 주절주절 쓸 수 있는 의견란은 해당 변환 결과의 신뢰도를 기계적으로 계산해내기에는 적합하지 않기 때문에 제외했습니다.

**Comment by taeyoonme** [comment]
영어는 혹시 지원계획 없나요~?

**Comment by sublee** [comment]
@taeyoonme 네, 영어는 철자로부터 한 가지 발음을 유추할 수 없고 역사적인 예외가 많아서 Hangulize 시스템으로는 지원할 수 없습니다.

**Comment by taeyoonme** [comment]
답변에 감사드립니다.

**Comment by sublee** [comment]
Hangulize 2에 도입할 수도 있습니다. 운선순위는 낮습니다.
